# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u7cfb\u7edf\u540d\u5b57', max_length=96, verbose_name='\u540d\u5b57')),
            ],
            options={
                'db_table': 'Device_System',
                'verbose_name': '\u7cfb\u7edf',
                'verbose_name_plural': '\u7cfb\u7edf',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '\u8bbe\u5907', 'verbose_name_plural': '\u8bbe\u5907'},
        ),
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='System', to='Device.System', verbose_name='\u8bbe\u5907\u6240\u5c5e\u7cfb\u7edf'),
        ),
    ]
