# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0004_auto_20190623_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='device2device',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.System', verbose_name='\u8bbe\u5907\u6240\u5c5e\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='device',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.System', verbose_name='\u8bbe\u5907\u6240\u5c5e\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon1',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='\u8bbe\u5907\u62d3\u6251\u56fe\u72b6\u60011\u56fe\u6807'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon2',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='\u8bbe\u5907\u62d3\u6251\u56fe\u72b6\u60012\u56fe\u6807'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon3',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='\u8bbe\u5907\u62d3\u6251\u56fe\u72b6\u60013\u56fe\u6807'),
        ),
    ]
