# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0009_auto_20190626_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isshow',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u865a\u62df\u8bbe\u5907'),
        ),
    ]
