# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0011_auto_20190627_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isrun',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a\u52a8\u6001\u56fe'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='isrun',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u51b3\u5b9a\u8bbe\u5907\u8fd0\u884c\u505c\u6b62\u8fdb\u800c\u5f71\u54cd\u903b\u8f91\u56fe\u4e2d\u662f\u5426\u663e\u793a\u52a8\u6001\u56fe'),
        ),
        migrations.AlterField(
            model_name='device2device',
            name='mid',
            field=models.TextField(blank=True, default='', null=True, verbose_name='\u7ebf\u8def\u4e2d\u95f4\u70b9\u4f4d'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.IntegerField(default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
