# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-01 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0014_auto_20190722_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 1, 2, 14, 40, 902000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device2device',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.Sensor', verbose_name='\u8fde\u63a5\u4f20\u611f\u5668'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, default='\u2103', max_length=96, null=True, verbose_name='\u70b9\u4f4d\u5355\u4f4d'),
        ),
    ]
