# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0015_auto_20190801_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='device2device',
            name='show_direction',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u6d41\u5411'),
        ),
    ]
