# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-02 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0017_device_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='position',
            new_name='label_position',
        ),
    ]
