# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0019_device2device_line_style_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device2device',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Device.Sensor', verbose_name='\u8fde\u63a5\u4f20\u611f\u5668'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='lastdata',
            field=models.CharField(blank=True, default='\u6700\u65b0\u6570\u503c', max_length=96, null=True, verbose_name='\u6700\u65b0\u6570\u503c'),
        ),
    ]
