# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-09-19 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0023_sensordata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensordata',
            table='Device_SensorData',
        ),
    ]
