# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-09-19 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0024_auto_20190919_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
