# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-09-19 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0025_auto_20190919_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=96, null=True, verbose_name='\u4f20\u611f\u5668\u6570\u636e')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='\u8bb0\u5f55\u65f6\u95f4')),
                ('mark', models.CharField(blank=True, max_length=96, null=True, verbose_name='\u6807\u8bb0')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.Sensor')),
            ],
            options={
                'db_table': 'Device_SensorData',
            },
        ),
    ]
