# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0027_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lastdata',
            field=models.TextField(blank=True, null=True, verbose_name='\u6700\u65b0\u6570\u636ejson'),
        ),
    ]
