# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-14 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0028_device_lastdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device2User', to=settings.AUTH_USER_MODEL),
        ),
    ]
