# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0029_auto_20191014_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerTuYa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(verbose_name='\u4efb\u52a1\u63cf\u8ff0')),
                ('data', models.TextField(verbose_name='\u5b9a\u65f6\u5185\u5bb9')),
            ],
            options={
                'db_table': 'Device_Timer',
            },
        ),
    ]
