# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-11 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Device', '0030_timertuya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u9879\u76ee', max_length=96, verbose_name='\u540d\u5b57')),
                ('position', models.CharField(default='[]', max_length=96, verbose_name='\u7ecf\u7eac\u5ea6')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Device_Project',
                'verbose_name': '\u7cfb\u7edf',
                'verbose_name_plural': '\u7cfb\u7edf',
            },
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u7cfb\u7edf\u7c7b\u578b\u540d\u5b57', max_length=96, verbose_name='\u540d\u5b57')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Device_SystemType',
                'verbose_name': '\u7cfb\u7edf',
                'verbose_name_plural': '\u7cfb\u7edf',
            },
        ),
        migrations.AlterModelOptions(
            name='timertuya',
            options={'verbose_name': '\u63d2\u5ea7\u5b9a\u65f6\u7b56\u7565', 'verbose_name_plural': '\u63d2\u5ea7\u5b9a\u65f6\u7b56\u7565'},
        ),
        migrations.AddField(
            model_name='device',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device2Users', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf\u8bbe\u5907\u7684\u4eba'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device2User', to=settings.AUTH_USER_MODEL, verbose_name='\u8bbe\u5907\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='system',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='system',
            name='system_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.SystemType', verbose_name='\u7cfb\u7edf\u7c7b\u578b\u540d\u5b57'),
        ),
    ]
