# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-11 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0032_auto_20191111_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(related_name='device2Users', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf\u8bbe\u5907\u7684\u4eba'),
        ),
    ]
