# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-14 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0033_auto_20191111_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u9879\u76ee', 'verbose_name_plural': '\u9879\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='systemtype',
            options={'verbose_name': '\u7cfb\u7edf\u7c7b\u578b', 'verbose_name_plural': '\u7cfb\u7edf\u7c7b\u578b'},
        ),
        migrations.AddField(
            model_name='system',
            name='order',
            field=models.IntegerField(default=1, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lastdata',
            field=models.TextField(blank=True, default='{}', null=True, verbose_name='\u6700\u65b0\u6570\u636ejson'),
        ),
        migrations.AlterField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='device2Users', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf\u8bbe\u5907\u7684\u4eba'),
        ),
    ]
