# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-12-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0035_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='infraed',
            field=models.TextField(blank=True, default='{}', null=True, verbose_name='\u7ea2\u5916\u53c2\u6570'),
        ),
    ]
