# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-22 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u672a\u547d\u540d\u8bbe\u5907', max_length=96, verbose_name='\u540d\u5b57')),
            ],
            options={
                'db_table': 'Device_Device',
                'verbose_name': '\u8bbe\u5907\u7c7b\u578b',
                'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u672a\u547d\u540d\u8bbe\u5907\u7c7b\u578b', max_length=96, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('icon', models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u8bbe\u5907\u62d3\u6251\u56fe\u56fe\u6807')),
            ],
            options={
                'db_table': 'Device_DeviceType',
                'verbose_name': '\u8bbe\u5907\u7c7b\u578b',
                'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='devicetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device', to='Device.DeviceType', verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
    ]
