# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_auto_20190623_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device2Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_from', models.CharField(default='1,2', max_length=96, verbose_name='\u8fde\u63a5\u8bbe\u5907\u5728\u903b\u8f91\u56fe\u4e2d\u4f4d\u7f6e')),
                ('position_to', models.CharField(default='1,2', max_length=96, verbose_name='\u88ab\u8fde\u63a5\u8bbe\u5907\u5728\u903b\u8f91\u56fe\u4e2d\u4f4d\u7f6e')),
                ('connection', models.CharField(default='\u8fde\u63a5\u65b9\u5f0f1', max_length=96, verbose_name='\u8fde\u63a5\u65b9\u5f0f')),
                ('device_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceFrom', to='Device.Device', verbose_name='\u8fde\u63a5\u8bbe\u5907')),
                ('device_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceTo', to='Device.Device', verbose_name='\u88ab\u8fde\u63a5\u8bbe\u5907')),
            ],
            options={
                'db_table': 'Device2Device',
                'verbose_name': '\u8bbe\u5907\u8fde\u63a5',
                'verbose_name_plural': '\u8bbe\u5907\u8fde\u63a5',
            },
        ),
    ]
