# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0006_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u70b9\u4f4d\u540d\u5b57', max_length=96, verbose_name='\u70b9\u4f4d\u540d\u5b57')),
                ('lastdata', models.CharField(default='\u6700\u65b0\u6570\u503c', max_length=96, verbose_name='\u6700\u65b0\u6570\u503c')),
            ],
            options={
                'db_table': 'Device_Sensor',
                'verbose_name': '\u8bbe\u5907\u8fde\u63a5',
                'verbose_name_plural': '\u8bbe\u5907\u8fde\u63a5',
            },
        ),
        migrations.AddField(
            model_name='device2device',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.Sensor', verbose_name='\u8fde\u63a5\u4f20\u611f\u5668'),
        ),
    ]
