# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-27 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0010_device_isshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='isshow',
        ),
        migrations.AddField(
            model_name='device2device',
            name='mid',
            field=models.TextField(default='', null=True, verbose_name='\u7ebf\u8def\u4e2d\u95f4\u70b9\u4f4d'),
        ),
    ]
