# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0013_devicetype_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='size',
            field=models.CharField(default='200,100', max_length=96, verbose_name='\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.IntegerField(default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
