# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0020_auto_20190805_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='opc \u534f\u8baeItemName snmp oid modbus \u5bc4\u5b58\u5668\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='datatype',
            field=models.TextField(blank=True, null=True, verbose_name='\u89e3\u6790\u65b9\u5f0fjson'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u91c7\u96c6IP\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='modbus_device_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='re_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5bc4\u5b58\u5668\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='xieyi',
            field=models.CharField(blank=True, choices=[('opc', 'opc'), ('snmp', 'snmp'), ('modbus', 'modbus')], max_length=96, null=True, verbose_name='code'),
        ),
    ]
