# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(blank=True, null=True)),
                ('appid', models.CharField(default='', max_length=64, verbose_name='\u5fae\u4fe1appid')),
                ('psw', models.CharField(default='', max_length=64, verbose_name='\u5fae\u4fe1\u516c\u4f17\u53f7\u5bc6\u7801')),
                ('yuming', models.CharField(default='', max_length=255, verbose_name='\u57df\u540d')),
                ('color', models.CharField(default='', max_length=255, verbose_name='\u989c\u8272')),
                ('front', models.CharField(default='', max_length=255, verbose_name='\u5b57\u4f53')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u914d\u7f6e',
                'verbose_name_plural': '\u7cfb\u7edf\u914d\u7f6e',
            },
        ),
    ]
