# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'\xe6\x91\x84\xe5\x83\x8f\xe5\xa4\xb4\xe5\x90\x8d\xe5\xad\x97')),
                ('code', models.CharField(max_length=64, verbose_name=b'\xe6\x91\x84\xe5\x83\x8f\xe5\xa4\xb4\xe7\xbc\x96\xe7\xa0\x81')),
                ('datatype', models.CharField(default=b'', max_length=64, verbose_name=b'\xe6\x91\x84\xe5\x83\x8f\xe5\xa4\xb4\xe6\x95\xb0\xe6\x8d\xae\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('addr', models.TextField(default=b'', max_length=128, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe5\x9c\xb0\xe5\x9d\x80')),
                ('ip', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'ip\xe5\x9c\xb0\xe5\x9d\x80')),
                ('cameraUuid', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe6\x91\x84\xe5\x83\x8f\xe6\x9c\xba\xe5\xaf\xb9\xe5\xba\x94\xe6\xb5\xb7\xe5\xba\xb78700cameraUuid')),
                ('onLineStatus', models.IntegerField(choices=[(1, b'\xe5\x9c\xa8\xe7\xba\xbf'), (0, b'\xe4\xb8\x8d\xe5\x9c\xa8\xe7\xba\xbf')], default=1, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x9c\xa8\xe7\xba\xbf')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'SMT_Camera',
            },
        ),
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('type', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe8\xa7\x84\xe6\xa0\xbc')),
                ('dataype', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('port', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3')),
                ('brand', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\x93\x81\xe7\x89\x8c')),
                ('power', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe7\x94\xb5\xe6\xba\x90')),
                ('ccd', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'ccd')),
                ('lens', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe9\x95\x9c\xe5\xa4\xb4')),
                ('ratio', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\x88\x86\xe8\xbe\xa8\xe7\x8e\x87')),
                ('temperature', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\xb7\xa5\xe4\xbd\x9c\xe6\xb8\xa9\xe5\xba\xa6')),
                ('humidity', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\xb7\xa5\xe4\xbd\x9c\xe6\xb9\xbf\xe5\xba\xa6')),
            ],
            options={
                'db_table': 'SMT_CameraType',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footfallStartTime', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\xae\xa2\xe6\xb5\x81\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('footfallEndTime', models.DateTimeField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\xae\xa2\xe6\xb5\x81\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('footfallTime', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'\xe5\xae\xa2\xe6\xb5\x81\xe6\x97\xb6\xe9\x97\xb4')),
                ('passengersIn', models.IntegerField(blank=True, null=True, verbose_name=b'\xe8\xbf\x9b\xe5\xae\xa2\xe6\xb5\x81\xe9\x87\x8f')),
                ('passengersOut', models.IntegerField(blank=True, null=True, verbose_name=b'\xe5\x87\xba\xe5\xae\xa2\xe6\xb5\x81\xe9\x87\x8f')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMT.Camera')),
            ],
            options={
                'db_table': 'SMT_peole',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMT.CameraType'),
        ),
        migrations.AddField(
            model_name='camera',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Space.Floor'),
        ),
        migrations.AddField(
            model_name='camera',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Camera', to='Space.Room'),
        ),
    ]
