# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20180303_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='./media'),
        ),
    ]
