# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildnum', models.CharField(max_length=64, null=True, verbose_name='\u697c\u53f7')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='\u540d\u79f0')),
                ('area', models.CharField(default='0', max_length=64, null=True, verbose_name='\u5efa\u7b51\u9762\u79ef')),
                ('cost', models.CharField(max_length=64, null=True, verbose_name='\u5de5\u7a0b\u9020\u4ef7')),
                ('typed', models.CharField(max_length=64, null=True, verbose_name='\u5de5\u7a0b\u7c7b\u578b')),
                ('builder', models.CharField(max_length=64, null=True, verbose_name='\u5efa\u8bbe\u5355\u4f4d')),
                ('constrator', models.CharField(max_length=64, null=True, verbose_name='\u65bd\u5de5\u5355\u4f4d')),
                ('supervisor', models.CharField(max_length=64, null=True, verbose_name='\u76d1\u7406\u5355\u4f4d')),
                ('piuTime', models.DateTimeField(null=True, verbose_name='\u6295\u5165\u4f7f\u7528\u65f6\u95f4')),
                ('project_url', models.CharField(max_length=256, null=True, verbose_name='\u9879\u76ee\u7f51\u5740')),
                ('summary', models.TextField(null=True, verbose_name='\u9879\u76ee\u7b80\u4ecb')),
                ('sequence', models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u5b57\u6bb5')),
            ],
            options={
                'db_table': 'SpaceManage_facility',
                'verbose_name': '\u697c\u5b87',
                'verbose_name_plural': '\u697c\u5b87',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u697c\u5c42\u540d\u79f0')),
                ('level', models.CharField(max_length=64, verbose_name='\u6807\u9ad8')),
                ('sign', models.CharField(max_length=64, verbose_name='\u6807\u8bb0')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u7cfb\u6570')),
                ('description', models.TextField(verbose_name='\u697c\u5c42\u63cf\u8ff0')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u9762\u79ef')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Space.Facility', verbose_name='\u5355\u4f4d\u5de5\u7a0b')),
            ],
            options={
                'db_table': 'SpaceManage_floor',
                'verbose_name': '\u5efa\u7b51\u9762\u79ef/\u5b9e\u9645\u4f7f\u7528\u9762\u79ef',
                'verbose_name_plural': '\u5efa\u7b51\u9762\u79ef/\u5b9e\u9645\u4f7f\u7528\u9762\u79ef',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u623f\u95f4\u53f7')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u623f\u95f4\u7f16\u53f7')),
                ('NetArea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u4f7f\u7528\u9762\u79ef')),
                ('GrossArea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u5efa\u7b51\u9762\u79ef')),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='\u79df\u91d1')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('roomTag', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u623f\u95f4\u6807\u8bb0')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='Space.Floor', verbose_name='\u697c\u5c42ID')),
            ],
            options={
                'db_table': 'SpaceManage_room',
            },
        ),
    ]
