# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-21 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u672a\u547d\u540d\u8bbe\u5907', max_length=96, verbose_name='\u540d\u5b57')),
                ('status', models.IntegerField(default=1, verbose_name='\u72b6\u6001')),
                ('isrun', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a\u52a8\u6001\u56fe')),
            ],
            options={
                'db_table': 'Device_Device',
                'verbose_name': '\u8bbe\u5907',
                'verbose_name_plural': '\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u672a\u547d\u540d\u8bbe\u5907\u7c7b\u578b', max_length=96, verbose_name='\u7c7b\u578b\u540d\u79f0')),
            ],
            options={
                'db_table': 'Device_DeviceType',
                'verbose_name': '\u8bbe\u5907\u7c7b\u578b',
                'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u70b9\u4f4d\u540d\u5b57', max_length=96, verbose_name='\u70b9\u4f4d\u540d\u5b57')),
                ('lastdata', models.CharField(blank=True, default='\u6700\u65b0\u6570\u503c', max_length=96, null=True, verbose_name='\u6700\u65b0\u6570\u503c')),
                ('unit', models.CharField(blank=True, default='\u2103', max_length=96, null=True, verbose_name='\u70b9\u4f4d\u5355\u4f4d')),
                ('isnumber', models.BooleanField(default=True, verbose_name='\u662f\u5426\u662f\u6570\u503c\u91cf')),
                ('status', models.IntegerField(default=1, verbose_name='\u72b6\u6001')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sensor', to='Device.Device', verbose_name='\u8bbe\u5907')),
            ],
            options={
                'db_table': 'Device_Sensor',
                'verbose_name': '\u4f20\u611f\u5668',
                'verbose_name_plural': '\u4f20\u611f\u5668',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=96, null=True, verbose_name='\u4f20\u611f\u5668\u6570\u636e')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='\u8bb0\u5f55\u65f6\u95f4')),
                ('mark', models.CharField(blank=True, max_length=96, null=True, verbose_name='\u6807\u8bb0')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.Sensor')),
            ],
            options={
                'db_table': 'Device_SensorData',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='devicetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device', to='Device.DeviceType', verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
    ]
