# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-21 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='areax',
            field=models.CharField(default='', max_length=96, verbose_name='x\u5750\u6807'),
        ),
        migrations.AddField(
            model_name='device',
            name='areay',
            field=models.CharField(default='', max_length=96, verbose_name='y\u5750\u6807'),
        ),
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(default='', max_length=96, verbose_name='\u8bbe\u5907\u7f16\u7801'),
        ),
    ]
