# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-02 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi', models.CharField(blank=True, max_length=1, null=True, verbose_name='\u5b57')),
                ('bihua', models.IntegerField(default=0, verbose_name='\u5eb7\u7199\u7b14\u753b')),
                ('wuxing', models.IntegerField(choices=[(1, '\u91d1'), (2, '\u6728'), (3, '\u6c34'), (4, '\u706b'), (5, '\u571f')], default=1, verbose_name='\u4e94\u884c\u5c5e\u6027')),
            ],
            options={
                'verbose_name': '\u5eb7\u7199\u8bcd\u5178',
                'verbose_name_plural': '\u5eb7\u7199\u8bcd\u5178',
            },
        ),
    ]
