# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-02 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kangxi', '0002_wuge'),
    ]

    operations = [
        migrations.AddField(
            model_name='wuge',
            name='jx',
            field=models.TextField(default='\u5409', max_length=12, verbose_name='\u5409\u51f6'),
        ),
        migrations.AddField(
            model_name='wuge',
            name='jx_index',
            field=models.IntegerField(choices=[(1, '\u5927\u5409'), (2, '\u5409'), (3, '\u51f6'), (4, '\u51f6')], default=0, verbose_name='\u5409\u51f6\u6570'),
        ),
    ]
