# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-26 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kangxi', '0003_auto_20190602_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuge',
            name='jx_index',
            field=models.IntegerField(choices=[(1, '\u5927\u5409'), (2, '\u5409'), (3, '\u51f6'), (4, '\u5927\u51f6')], default=0, verbose_name='\u5409\u51f6\u6570'),
        ),
    ]
