version: "2"
services:
  redis:
    build : ./redis
    restart : always
    container_name : redis
    ports:
      - "8080:6379" 
  timedtask:
    build : ./timedtask
    restart: always
    container_name: timedtask
    privileged: true
    ports:
     - "127.0.0.1:8000:5000"
    volumes:
     - /root/fullstack/docker-com/timedtask/TimedTask:/var/www
  db:
    image: mysql:5.5
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zzkjyunwei
  django:
    build : ./django
    restart: always
    container_name: django
    privileged: true
    # environment:
    #   project: any
    volumes:
     - /root/fullstack/docker-com/django/code:/app
  nginx-host:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - timedtask
      - django
    container_name: nginx-host
