# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-22 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 22, 7, 26, 47, 564127, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 8, 22, 7, 26, 56, 58845, tzinfo=utc), verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 22, 7, 27, 2, 265738, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_update_datetime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 8, 22, 7, 27, 21, 575844, tzinfo=utc), verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
