# -*- coding: utf-8 -*-
"""
Django settings for any project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from __future__ import absolute_import
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4)2s8ad#)wenb&#y(sy#g^z&z3=@shcu7j4vw)8@a1k!zr7x+-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '39.107.127.87',
    'shuhuhu.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'ckeditor',
    'ckeditor_uploader',
    'first',
]
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100
}
MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'any.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.split( os.path.dirname(__file__))[0],'templates').replace('\\','/'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'any.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            #'NAME': 'scc4pms',
            # 'NAME': 'xhyyfm',

            'NAME': 'jha',
            'USER':'root',
            'PASSWORD':'zzkjyunwei',
            'HOST':'116.62.228.242',
            'PORT':3306,
        },


}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    ("css",os.path.join(STATIC_ROOT, 'css')),
    ("js",os.path.join(STATIC_ROOT, 'js')),
    ("image",os.path.join(STATIC_ROOT, 'image')),
    ("img",os.path.join(STATIC_ROOT, 'img')),
    ("images",os.path.join(STATIC_ROOT, 'images')),
    ("fonts",os.path.join(STATIC_ROOT, 'fonts')),
    ("ckeditor",os.path.join(STATIC_ROOT, 'ckeditor')),
    ("rs-plugin",os.path.join(STATIC_ROOT, 'rs-plugin')),
)

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media').replace("\\","/")
STATIC_PATH=MEDIA_ROOT

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = 'uploads/'
# CKEDITOR_JQUERY_URL = 'js/jquery-3.2.1.min.js'
CKEDITOR_FILENAME_GENERATOR = 'any.utils.get_filename'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'language': 'zh-Hans',
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'clipboard', 'items': ['Undo', 'Redo', '-', 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote']},
            {'name': 'insert', 'items': ['Image', 'Table', 'HorizontalRule', 'Smiley']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-']},
            {'name': 'tools', 'items': ['Maximize']},
            '/',
            {'name': 'styles', 'items': ['Format', 'Font', 'FontSize']},
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'paragraph',
             'items': ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'document', 'items': ['Source']},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'width': '100%',
        'cols': '50',
        'rows': '20',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_BROWSE_SHOW_DIRS = True


MENUS = [
    {
        'name': '首页',
        'link': '/index',
        'chirld': [],
        'active':False
    },
    
    {
        'name': '新闻资讯',
        'link': '/o/news',
        'active':False,
        'chirld': [
            {
                'name': '公司新闻',
                'link': '/',
            },
            {
                'name': '行业新闻',
                'link': '/',
            },
        ],
    },
    {
        'name': '关于我们',
        'link': '/o/about',
        'active':False,
        'chirld': [
            {
                'name': '公司简介',
                'link': '/',
            },
            {
                'name': '董事长致辞',
                'link': '/',
            },
            {
                'name': '组织架构',
                'link': '/',
            },
            {
                'name': '发展历程',
                'link': '/',
            },
            {
                'name': '资质荣誉',
                'link': '/',
            },
        ],
    },
    {
        'name': '业务范围',
        'link': '/o/yewu',
        'active':False,
        'chirld': [
            {
                'name': '机场内部设备',
                'link': '/',
            },
            {
                'name': '航站楼',
                'link': '/',
            },
            {
                'name': '跑道灯光',
                'link': '/',
            },
            {
                'name': '雷达通信',
                'link': '/',
            },
        ],
    },
    {
        'name': '项目展示',
        'link': '/o/xiangmu',
        'active':False,
        'chirld': [
            {
                'name': '国内工程',
                'link': '/',
            },
            {
                'name': '国外工程',
                'link': '/',
            },
        ],
    },
    {
        'name': '企业文化',
        'link': '/o/',
        'active':False,
        'chirld': [
            {
                'name': '企业愿景',
                'link': '/',
            },
            {
                'name': '社会责任',
                'link': '/',
            },
            {
                'name': '员工风采',
                'link': '/',
            },
        ],
    },
    {
        'name': '人力资源',
        'link': '/o/',
        'active':False,
        'chirld': [
            {
                'name': '人才理念',
                'link': '/',
            },
            {
                'name': '招聘信息',
                'link': '/',
            },
        ],
    },
    {
        'name': '联系我们',
        'link': '/',
        'active':False,
        'chirld': [],
    },
]