# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-22 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='images',
        ),
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.RemoveField(
            model_name='other',
            name='images',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='images',
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
