# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-22 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20181022_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': '\u5176\u4ed6', 'verbose_name_plural': '\u5176\u4ed6'},
        ),
    ]
