# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-22 02:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20181022_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='en_txt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe6\x96\xb0\xe9\x97\xbb\xe5\x86\x85\xe5\xae\xb9\xe8\x8b\xb1\xe6\x96\x87'),
        ),
        migrations.AlterField(
            model_name='news',
            name='txt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe6\x96\xb0\xe9\x97\xbb\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='en_txt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe8\x8c\x83\xe5\x9b\xb4\xe5\x86\x85\xe5\xae\xb9\xe8\x8b\xb1\xe6\x96\x87'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='txt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe8\x8c\x83\xe5\x9b\xb4\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
