# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20181022_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='first.File', verbose_name=b'\xe6\x96\xb0\xe9\x97\xbb\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='first.File', verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe8\x8c\x83\xe5\x9b\xb4\xe5\x9b\xbe\xe7\x89\x87'),
        ),
    ]
