# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-23 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20181022_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '\u7d20\u6750', 'verbose_name_plural': '\u7d20\u6750'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 23, 2, 58, 55, 905000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'upload/', verbose_name=b'\xe7\xb4\xa0\xe6\x9d\x90\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AddField(
            model_name='file',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=b'upload/thumb', verbose_name=b'\xe7\xb4\xa0\xe6\x9d\x90\xe5\xbe\xae\xe7\xbc\xa9\xe5\x9b\xbe'),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name=b'\xe7\xb4\xa0\xe6\x9d\x90\xe6\xa0\x87\xe9\xa2\x98'),
        ),
    ]
