# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-23 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20181023_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(upload_to=b'upload/', verbose_name=b'\xe7\xb4\xa0\xe6\x9d\x90\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AlterField(
            model_name='news',
            name='t',
            field=models.IntegerField(choices=[(1, b'\xe8\xa1\x8c\xe4\xb8\x9a\xe8\xb5\x84\xe8\xae\xaf'), (2, b'\xe5\x85\xac\xe5\x8f\xb8\xe6\x96\xb0\xe9\x97\xbb')], default=1, verbose_name=b'\xe4\xbc\x81\xe4\xb8\x9a\xe6\x96\xb0\xe9\x97\xbb/\xe5\x85\xac\xe5\x8f\xb8\xe6\x96\xb0\xe9\x97\xbb'),
        ),
    ]
