# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-24 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20181023_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLIDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name=b'\xe7\xb4\xa0\xe6\x9d\x90\xe6\xa0\x87\xe9\xa2\x98')),
                ('image', models.ImageField(upload_to=b'upload/', verbose_name=b'\xe7\xb4\xa0\xe6\x9d\x90\xe5\x9b\xbe\xe7\x89\x87')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=b'upload/thumb', verbose_name=b'\xe7\xb4\xa0\xe6\x9d\x90\xe5\xbe\xae\xe7\xbc\xa9\xe5\x9b\xbe')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u9996\u9875\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad\u56fe',
            },
        ),
    ]
