# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-25 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='file',
            field=models.FileField(default=datetime.datetime(2018, 10, 25, 7, 9, 25, 428000, tzinfo=utc), upload_to=b'upload/', verbose_name=b'\xe5\xbd\x95\xe6\x92\xad\xe8\xa7\x86\xe9\xa2\x91'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to=b'upload/', verbose_name=b'\xe8\xbd\xae\xe6\x92\xad\xe5\x9b\xbe\xe7\x89\x87'),
        ),
    ]
