# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20181025_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'upload/', verbose_name=b'\xe5\xbd\x95\xe6\x92\xad\xe8\xa7\x86\xe9\xa2\x91'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'upload/', verbose_name=b'\xe8\xbd\xae\xe6\x92\xad\xe5\x9b\xbe\xe7\x89\x87'),
        ),
    ]
