# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-25 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_auto_20181025_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(default='', upload_to=b'upload/', verbose_name=b'\xe8\xbd\xae\xe6\x92\xad\xe5\x9b\xbe\xe7\x89\x87'),
            preserve_default=False,
        ),
    ]
